"""
HEILO Seed Code — modelo PRÓPRIO de código, treinado do zero (Colab).

Mesma base do HEILO Seed (GPT decoder + tokenizer BPE próprio), mas lendo só
código Python público. Não usa pesos de nenhum modelo externo.

Expectativa honesta: com ~30 M parâmetros e algumas horas de GPU ele aprende a
sintaxe e padrões comuns do Python (autocompletar funções simples). Não entende
pedidos complexos nem substitui um programador.

Avaliação real (nada de "parece bom"):
- perda/perplexidade em código de validação que nunca entrou no treino
- % de completações que são Python válido (ast.parse)
- pass@1: a função completada PASSA nos testes (executados de verdade, com tempo limite)
"""
from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable, Dict, Iterator, List

from heilo.models.seed.gpt import GPTConfig

CONFIG_CODE = GPTConfig(block_size=512, n_layer=8, n_head=8, n_embd=512, dropout=0.05)
VOCAB_CODE = 16000


# ------------------------------------------------------------------- corpus
def limpar_codigo(texto: str) -> str:
    """Descarta arquivos gerados automaticamente, minificados ou gigantes."""
    if not texto or len(texto) > 60_000 or len(texto) < 200:
        return ""
    linhas = texto.split("\n")
    if max(len(l) for l in linhas) > 300:
        return ""
    cab = texto[:600].lower()
    if "auto-generated" in cab or "autogenerated" in cab or "do not edit" in cab:
        return ""
    return texto


def textos_python(max_chars: int, log: Callable[[str], None] = print) -> Iterator[str]:
    """Código Python público (codeparrot-clean, Hugging Face, streaming). Só onde há internet."""
    from datasets import load_dataset
    ds = load_dataset("codeparrot/codeparrot-clean", split="train", streaming=True)
    total = 0
    for item in ds:
        t = limpar_codigo(item.get("content", ""))
        if not t:
            continue
        total += len(t)
        yield t
        if total >= max_chars:
            log(f"  corpus de código: {total:,} caracteres")
            return


# --------------------------------------------------------------- avaliação
# Problemas escritos para esta avaliação (não vêm do corpus). Fáceis de propósito:
# medem se o modelo aprendeu o básico, não se "programa como um especialista".
PROBLEMAS = [
    ("soma", 'def soma(a, b):\n    """Retorna a soma de a e b."""\n', "assert soma(2, 3) == 5\nassert soma(-1, 1) == 0"),
    ("eh_par", 'def eh_par(n):\n    """Retorna True se n for par."""\n', "assert eh_par(4)\nassert not eh_par(7)"),
    ("maior", 'def maior(lista):\n    """Retorna o maior número da lista."""\n', "assert maior([3, 9, 2]) == 9\nassert maior([-5, -2]) == -2"),
    ("inverter", 'def inverter(texto):\n    """Retorna o texto de trás para frente."""\n', "assert inverter('abc') == 'cba'"),
    ("somar_lista", 'def somar_lista(numeros):\n    """Soma todos os números da lista."""\n', "assert somar_lista([1, 2, 3]) == 6\nassert somar_lista([]) == 0"),
    ("fatorial", 'def fatorial(n):\n    """Retorna n! (fatorial de n)."""\n', "assert fatorial(5) == 120\nassert fatorial(0) == 1"),
    ("contar_vogais", 'def contar_vogais(texto):\n    """Conta quantas vogais (aeiou) existem no texto."""\n', "assert contar_vogais('banana') == 3"),
    ("quadrados", 'def quadrados(n):\n    """Retorna a lista [0, 1, 4, ...] com os quadrados de 0 até n-1."""\n', "assert quadrados(4) == [0, 1, 4, 9]"),
    ("media", 'def media(valores):\n    """Retorna a média aritmética da lista."""\n', "assert media([2, 4, 6]) == 4"),
    ("maiusculas", 'def maiusculas(texto):\n    """Retorna o texto em letras maiúsculas."""\n', "assert maiusculas('heilo') == 'HEILO'"),
    ("filtrar_pares", 'def filtrar_pares(numeros):\n    """Retorna só os números pares da lista."""\n', "assert filtrar_pares([1, 2, 3, 4]) == [2, 4]"),
    ("add", 'def add(x, y):\n    """Return the sum of x and y."""\n', "assert add(1, 2) == 3"),
    ("is_empty", 'def is_empty(items):\n    """Return True if the list is empty."""\n', "assert is_empty([])\nassert not is_empty([1])"),
    ("first", 'def first(items):\n    """Return the first element of the list."""\n', "assert first([7, 8]) == 7"),
    ("count_words", 'def count_words(text):\n    """Return the number of words in text."""\n', "assert count_words('a b c') == 3"),
    ("minimo", 'def minimo(a, b):\n    """Retorna o menor entre a e b."""\n', "assert minimo(3, 8) == 3\nassert minimo(5, -1) == -1"),
    ("dobro_lista", 'def dobro_lista(numeros):\n    """Retorna uma lista com o dobro de cada número."""\n', "assert dobro_lista([1, 2]) == [2, 4]"),
    ("ler_arquivo", 'def ler_arquivo(caminho):\n    """Lê e retorna todo o conteúdo de um arquivo de texto."""\n', "import tempfile, os\nf = tempfile.NamedTemporaryFile('w', delete=False, suffix='.txt'); f.write('oi'); f.close()\nassert ler_arquivo(f.name) == 'oi'"),
    ("chaves_ordenadas", 'def chaves_ordenadas(d):\n    """Retorna as chaves do dicionário em ordem alfabética."""\n', "assert chaves_ordenadas({'b': 1, 'a': 2}) == ['a', 'b']"),
    ("mm_para_pol", 'def mm_para_pol(mm):\n    """Converte milímetros para polegadas (1 pol = 25.4 mm)."""\n', "assert abs(mm_para_pol(25.4) - 1) < 1e-9"),
]


def cortar_corpo(completacao: str) -> str:
    """Mantém só o corpo da função (linhas indentadas); para no 1º código de nível 0."""
    corpo = []
    for l in completacao.split("\n"):
        if l.strip() and not l.startswith((" ", "\t")):
            break
        corpo.append(l)
    return "\n".join(corpo).rstrip() + "\n"


def executar_teste(codigo: str, teste: str, tempo: int = 5) -> bool:
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False, encoding="utf-8") as f:
        f.write(codigo + "\n" + teste + "\n")
        caminho = f.name
    try:
        r = subprocess.run([sys.executable, caminho], capture_output=True, timeout=tempo)
        return r.returncode == 0
    except subprocess.TimeoutExpired:
        return False
    finally:
        Path(caminho).unlink(missing_ok=True)


def completar(modelo, prompt: str, temperatura: float = 1.0, top_k: int = 1,
              max_novos: int = 160) -> str:
    tok = modelo.tokenizer
    ids = [tok.doc] + tok.encode(prompt)
    novos = modelo.gerar(ids[-modelo.cfg.block_size:], max_novos=max_novos, temperatura=temperatura,
                         top_k=top_k, parar_em=(tok.fim, tok.doc))
    return tok.decode(novos)


def avaliar_codigo(modelo, amostras: int = 5, log: Callable[[str], None] = print) -> Dict:
    """pass@1 (greedy), pass@k amostrado e % de código válido — com testes EXECUTADOS."""
    det, ok_greedy, ok_k, validos, total_amostras = [], 0, 0, 0, 0
    for nome, prompt, teste in PROBLEMAS:
        corpo = cortar_corpo(completar(modelo, prompt))
        codigo = prompt + corpo
        try:
            ast.parse(codigo); valido = True
        except SyntaxError:
            valido = False
        passou = valido and executar_teste(codigo, teste)
        algum = passou
        for _ in range(amostras):
            c = prompt + cortar_corpo(completar(modelo, prompt, temperatura=0.8, top_k=40))
            try:
                ast.parse(c); v = True
            except SyntaxError:
                v = False
            validos += v; total_amostras += 1
            if v and not algum and executar_teste(c, teste):
                algum = True
        ok_greedy += passou; ok_k += algum
        det.append({"problema": nome, "passou_greedy": passou, f"passou_em_{amostras + 1}": algum,
                    "valido": valido, "codigo": codigo})
        log(f"  {'✔' if passou else ('~' if algum else '✘')} {nome}")
    n = len(PROBLEMAS)
    return {"problemas": n, "pass@1": round(ok_greedy / n, 3), f"pass@{amostras + 1}": round(ok_k / n, 3),
            "codigo_valido": round(validos / max(1, total_amostras), 3), "detalhes": det}
